# Generated by Django 5.1.7 on 2026-04-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_premium_user_premium_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
