# Generated by Django 5.1.7 on 2026-04-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
        ('skillsessions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='skillsessions.session'),
        ),
    ]
