# Generated by Django 5.1.7 on 2026-03-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('skill_type', models.CharField(choices=[('teach', 'Teach'), ('learn', 'Learn')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
